version: "3.9"
services: 
  user-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgresroot
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=user_services
    ports: 
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      user-services-network:
        aliases:
          - user-db-host
volumes: 
  db:
networks: 
  user-services-network:
